# Generated by Django 3.1.4 on 2020-12-21 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesurements', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mesurements',
            new_name='mesurementsofdistance',
        ),
    ]
