# Generated by Django 3.1.4 on 2020-12-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesurements', '0002_auto_20201221_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesurementsofdistance',
            name='location',
            field=models.CharField(default='usa', max_length=85),
        ),
    ]
