# Generated by Django 3.1.4 on 2020-12-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesurements', '0004_auto_20201221_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesurementsofdistance',
            name='location',
            field=models.CharField(default='ddd', max_length=85),
        ),
    ]
